"use client";

import React from "react";
import { FaThumbsUp } from "react-icons/fa";
import Image from "next/image";

export default function TherapistCardRatedSummaryAI({
  summary,
  totalReviews = 0,
  helpfulCount = 0,
  isHelpful = false,
  onReaction,
}) {
  return (
    <div className="w-full max-w-[1050px]">
      <div className="flex flex-col gap-3 border-b border-solid border-amethyst-100 px-4 pb-4">
        {/* Header Section */}
        <div className="flex justify-between items-start h-14">
  <div className="w-full flex items-center justify-between gap-3 min-w-0">
    <div className="flex gap-3 min-w-0 flex-1">
      {/* AI Icon */}
      <div className="w-[53px] h-[53px] bg-gradient-to-b from-[#b9b1ff] to-[#9d93ff] rounded-full flex items-center justify-center flex-shrink-0">
        <Image
          src="/assets/icons-svg/others/AI.svg"
          alt="AI"
          width={28}
          height={28}
          className="filter brightness-0 invert"
        />
      </div>
      <div className="min-w-0 flex-1">
        {/* Title */}
        <div className="flex flex-col min-w-0">
          <h3 className="text-lg md:text-xl font-normal text-stone-800 font-['Outfit'] tracking-[-0.28px] truncate">
            Reviews Summary
          </h3>
          <span className="text-base font-light text-[#313131] font-['Outfit'] -mt-1 truncate">
            Generated by AI
          </span>
        </div>
      </div>
    </div>
    {/* Reviews Count */}

    <div className="px-4 py-1 bg-[#f3f1ff] rounded-full flex-shrink-0">
      <span className="hidden md:block text-sm text-[#7466f2] font-['Outfit'] truncate">
        Based on {totalReviews} reviews
      </span>

      <span className="md:hidden block text-sm text-[#7466f2] font-['Outfit'] truncate">
        {totalReviews} reviews
      </span>
    </div>
  </div>
</div>

        {/* Summary Content */}
        <div className="flex flex-col gap-3 pt-1">
          {/* Summary Text - mismo estilo que las reviews */}
          <p className="text-[13.5px] font-base text-stone-600 font-['poppins'] tracking-[0.16px] max-w-[720px] leading-6">
            {summary}
          </p>

          {/* Single Helpful Button */}
          <div className="flex items-center gap-2 pt-2 pb-4">
            <button
              onClick={() => onReaction && onReaction("ai-summary", "helpful")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full transition-all ${
                isHelpful
                  ? "bg-[#7466f2] text-white"
                  : "bg-stone-100 text-stone-600 hover:bg-stone-200"
              }`}
            >
              <FaThumbsUp className="text-sm" />
              <span className="text-xs font-medium font-['poppins']">
                Is this helpful? ({helpfulCount})
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
