"use client";

import React from "react";
import { FaThumbsUp } from "react-icons/fa";
import Image from "next/image";

export default function TherapistCardRatedSummaryAI({
  summary = "Based on 45 reviews, patients consistently praise this therapist's empathetic approach and effective techniques. Many report significant improvements in managing anxiety and making important life decisions. The safe, welcoming environment is frequently mentioned as a key factor in their therapeutic progress.",
  totalReviews = 45,
  helpfulCount = 87,
  isHelpful = false,
  onReaction,
}) {
  return (
    <div className="w-full max-w-[1050px]">
      <div className="flex flex-col gap-3 border-b border-solid border-amethyst-100 px-4 pb-4">
        {/* Header Section */}
        <div className="flex justify-between items-start h-14">
          <div className="flex items-center gap-3">
            {/* AI Icon */}
            <div className="w-[53px] h-[53px] bg-gradient-to-b from-[#b9b1ff] to-[#9d93ff] rounded-full flex items-center justify-center">
              <Image
                src="/assets/icons-svg/others/AI.svg"
                alt="AI"
                width={28}
                height={28}
                className="filter brightness-0 invert"
              />
            </div>

            {/* Title */}
            <div className="flex flex-col">
              <h3 className="text-xl font-normal text-stone-800 font-['Outfit'] tracking-[-0.28px]">
                Reviews Summary
              </h3>
              <span className="text-base font-light text-[#313131] font-['Outfit'] -mt-1">
                Generated by AI
              </span>
            </div>
          </div>

          {/* Reviews Count */}
          <div className="px-4 py-1 bg-[#f3f1ff] rounded-full">
            <span className="text-sm text-[#7466f2] font-['Outfit']">
              Based on {totalReviews} reviews
            </span>
          </div>
        </div>

        {/* Summary Content */}
        <div className="flex flex-col gap-3 pt-1">
          {/* Summary Text - mismo estilo que las reviews */}
          <p className="text-[13.5px] font-base text-stone-600 font-['poppins'] tracking-[0.16px] max-w-[720px] leading-6">
            {summary}
          </p>

          {/* Single Helpful Button */}
          <div className="flex items-center gap-2 pt-2 pb-4">
            <button
              onClick={() => onReaction && onReaction("ai-summary", "helpful")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full transition-all ${
                isHelpful
                  ? "bg-[#7466f2] text-white"
                  : "bg-stone-100 text-stone-600 hover:bg-stone-200"
              }`}
            >
              <FaThumbsUp className="text-sm" />
              <span className="text-xs font-medium font-['poppins']">
                Is this helpful? ({helpfulCount})
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
